### ISSUE TITLE
ludox experiment

### ISSUE THREAD

**Issue by dragonflyby666** [Cyril-Mergny/Europa-Experiment#1]
could you please help me with photos of ludox experiment?I actually didn't know how to get these photos,thanks!

**Comment by cmergny** [comment]
Hi,
This repository was focused only on the data-processing and DEM reconstructions for the Ludox experiment. I do not own the photos of the Ludox experiments, so I am not allowed to share them here. However if you want to have more info about it [here is an abstract from LPSC. ](https://www.hou.usra.edu/meetings/lpsc2022/pdf/1443.pdf) Feel free to contact the second author if you want to know more about the experiments :)

**Comment by dragonflyby666** [comment]
I got it！Thanks a lot！
I am an undergraduate from chengdu university of technology,major in planetary science.I am very interested in icy moon enceladus and.europa.So I am doing a small scientofic project about icy moon.haha!I am also preparing for studying abroad, yes absoluty considering&nbsp; france! Looking forward to making more communication with you!&nbsp; haha😁
chengyu zheng
chengdu, sichuan province,china



---Original---
From: "Cyril ***@***.***&gt;
Date: Mon, May 27, 2024 00:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cmergny/Europa-Experiment] ludox experiment (Issue #1)




 
Hi,
 This repository was focused only on the data-processing and DEM reconstructions for the Ludox experiment. I do not own the photos of the Ludox experiments, so I am not allowed to share them here. However if you want to have more info about it here is an abstract from LPSC.  Feel free to contact the second author if you want to know more about the experiments :)

**Comment by cmergny** [comment]
Wishing you the best for your project! :)
